version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xFrBQKZEdZKp
      POSTGRES_DB: movieapp

  app:
    build: .
    ports:
      - 4000:4000
    command: >
      sh -c "npx prisma migrate deploy
      && yarn start -p 4000"
    environment:
      DATABASE_URL: postgresql://postgres:xFrBQKZEdZKp@postgres:5432/movieapp?schema=public
    depends_on:
      - postgres
