version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xFrBQKZEdZKp
      POSTGRES_DB: movieapp
